FROM amazoncorretto:23-jdk
ARG JAR_FILE=build/libs/*.jar
ARG API_USERNAME=user
ARG API_PASSWORD=password
ARG DB_USERNAME=user
ARG DB_PASSWORD=password
ENV API_USERNAME=$API_USERNAME
ENV API_PASSWORD=$API_PASSWORD
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
