FROM amazoncorretto:23-jdk
ARG JAR_FILE=build/libs/*.jar
ARG DB_USERNAME=user
ARG DB_PASSWORD=password
ARG DB_DATABASE_NAME=postgres
ARG DB_CONTAINER=database
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DATABASE_NAME=$DB_DATABASE_NAME
ENV DB_CONTAINER=$DB_CONTAINER
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
