services:
  database:
    container_name: database
    env_file: database.env
    image: postgres:latest
  backend:
    container_name: backend
    depends_on:
     - "database"
    env_file: backend.env
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
  frontend:
    container_name: frontend
    depends_on:
     - "backend"
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
     - "80:80"


