services:
  database:
    container_name: database
    env_file: database.env
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 20
  backend:
    container_name: backend
    depends_on:
     - "database"
    env_file: backend.env
    build:
      context: ./backend
      dockerfile: ../backend.Dockerfile
    restart: always
  frontend:
    container_name: frontend
    depends_on:
     - "backend"
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
     - "80:80"


