services:
  database:
    container_name: database
    env_file: database.env
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 30s
      timeout: 5s
      retries: 3
  data-layer:
    container_name: data-layer
    depends_on:
      database:
        condition: service_healthy
    env_file: data-layer.env
    build:
      context: ./backend/data-layer
      dockerfile: ../../data-layer.Dockerfile
    restart: always
    ports:
     - "8080:8080"
  frontend:
    container_name: frontend
    depends_on:
     - "data-layer"
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
     - "80:80"


