services:
  database:
    container_name: database
    env_file: database.env
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
     - "5432:5432"
  data-layer:
    container_name: data-layer
    depends_on:
      database:
        condition: service_healthy
    env_file: data-layer.env
    build:
      context: ../backend/data-layer
      dockerfile: ../../docker/data-layer.Dockerfile
    restart: always
    ports:
     - "8080:8080"
  webscraper:
    container_name: webscraper
    depends_on:
     - "data-layer"
    env_file: webscraper.env
    build:
      context: ../backend/webscraper
      dockerfile: ../../docker/webscraper.Dockerfile
    restart: always
  frontend:
    container_name: frontend
    depends_on:
     - "data-layer"
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    ports:
     - "80:80"


