CREATE TABLE PEER_DATA (ID int PRIMARY KEY AUTO_INCREMENT, NAME varchar(8), STATE varchar(18), WAVE int, INTENSIVE int, XP int, PEER_REVIEW_POINTS int, CODE_REVIEW_POINTS int, COINS int );
INSERT INTO PEER_DATA (NAME, STATE, WAVE, INTENSIVE, XP, PEER_REVIEW_POINTS, CODE_REVIEW_POINTS, COINS) VALUES ('cypherco', 'ACTIVE', 2, 4, 999999, 999999, 9999999, 9999999);
